### ISSUE TITLE
Is this possible to run decode.py in Mac OS 10.14 | Query

### ISSUE THREAD

**Issue by bikee1235** [KartikTalwar/pied-piper#4]

**Comment by rraval** [comment]
Hi there,

I haven't looked at this code in literal ages, but `decode.py` is very linux specific (it uses the `alsaaudio` package to open the audio stream for the microphone).

There's some facility for opening pre-recording WAV files but that was used for interactive testing and debugging, and thus the code flow doesn't actually do any decoding.

If you're handy with python it wouldn't be super hard to fix. I'm a bit busy these days with $dayjob so I can't commit to any specific timeframe to fixing it myself.
